

--CREATE DATABASE

DROP DATABASE  IF EXISTS `EMIRATES`;


--CREATING TABLE FOR MEASSGES AND CHAT 
DROP TABLE IF EXISTS `MESSAGES`;

CREATE TABLE IF NOT EXISTS `MESSAGES`(
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(255) NOT NULL,
    `PROFESSION` VARCHAR(255) NOT NULL,
    `EMAIL`,VARCHAR(255) NOT NULL,
    `MESSAGE`,VARCHAR(255) NOT NULL,
    PRIMARY KEY(`ID`),
)ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=latin1;


--CREATING ONE DETAULT USER

INSERT INTO `MESSAGES` (`ID`,`NAME`,`PROFESSION`,`EMAIL`,`MESSAGE`) VALUES(`1`,`WARIO DUBA`,`EMIRATES DIRECTOR`,`warioduba45@gmail.com`,`Welcome all into ouy company where your are all welcomed here. Incase on anything  like comment or reaching us contat or send us an email`);

--DROPING TABLE USERS 

DROP  TABLE IF EXISTS `USERS`;


--Registering users for subcriptions
CREATE TABLE IF NOT EXISTS `USERS`(
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(255) NOT NULL,
    `EMAIL` VARCHAR(255) NOT NULL,
    PRIMARY KEY(`ID`),
    UNIQUE(`EMAIL`),
)ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=latin1;


