
DROP DATABASE  IF EXISTS `EMIRATES`;

CREATE DATABASE IF NOT EXISTS `EMIRATES`;




CREATE TABLE IF NOT EXISTS `MESSAGES`(
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(255) NOT NULL,
    `PROFESSION` VARCHAR(255) NOT NULL,
    `EMAIL`VARCHAR(255) NOT NULL,
    `MESSAGE`VARCHAR(255) NOT NULL,
    
    PRIMARY KEY(`ID`));


ALTER TABLE `messages` ADD `CREATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `MESSAGE`;
INSERT INTO `MESSAGES` (`ID`,`NAME`,`PROFESSION`,`EMAIL`,`MESSAGE`) VALUES('1','WARIO DUBA','EMIRATES DIRECTOR','warioduba45@gmail.com','Welcome all into ouy company where your are all welcomed here. Incase on anything  like comment or reaching us contat or send us an email');



DROP  TABLE IF EXISTS `USERS`;



CREATE TABLE IF NOT EXISTS `USERS`(
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(255) NOT NULL,
    `EMAIL` VARCHAR(255) NOT NULL,
    PRIMARY KEY(`ID`),
    UNIQUE(`EMAIL`));


